package me.randomHashTags.RandomPackage.utils;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/*
    This software is created and owned by RandomHashTags, and is licensed under the GNU Affero General Public License v3.0 (https://choosealicense.com/licenses/agpl-3.0/)
    You can only find this software at https://gitlab.com/RandomHashTags/umaterial
    You can find RandomHashTags (me) at
        Discord - RandomHashTags#1948
        Email - imrandomhashtags@gmail.com
        GitHub - https://github.com/RandomHashTags
        GitLab - https://gitlab.com/RandomHashTags
        MCMarket - https://www.mc-market.org/members/20858/
        PayPal - imrandomhashtags@gmail.com
        SpigotMC - https://www.spigotmc.org/members/randomhashtags.76364/
        Twitter - https://twitter.com/irandomhashtags
 */
public enum UMaterial {
    // <item>(1.8.8, 1.9.4, 1.10.2, 1.11.2, 1.12.2, 1.13.2, 1.14.0)
    // 1.8.8 = http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Material.html
    // 1.13.2 = https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    // 1.13.2 visual = https://www.digminecraft.com/lists/item_id_list_pc.php
    // Terracotta (Renamed from Stained Clay) = https://minecraft.gamepedia.com/Terracotta
    // Glazed Terracotta = https://minecraft.gamepedia.com/Glazed_Terracotta
    // Shulker boxes = https://minecraft.gamepedia.com/Shulker_Box
    // Glass Panes = https://minecraft.gamepedia.com/Glass_Pane
    // Wool = https://minecraft.gamepedia.com/Wool
    // Bed = https://minecraft.gamepedia.com/Bed
    // Spawn Eggs = https://minecraft.gamepedia.com/Spawn_Egg
    // Banner = https://minecraft.gamepedia.com/Banner
    // Carpet = https://minecraft.gamepedia.com/Carpet
    // Concrete = https://minecraft.gamepedia.com/Concrete
    // Concrete Powder = https://minecraft.gamepedia.com/Concrete_powder
    // Command Block = https://minecraft.gamepedia.com/Command_Block
    // Special blocks = https://www.planetminecraft.com/blog/secret-blocks-vanilla/
    ACACIA_BOAT(Arrays.asList("BOAT", null, null, null, null, "ACACIA_BOAT"), 0),
    ACACIA_BUTTON(Arrays.asList("WOOD_BUTTON", null, null, null, null, "ACACIA_BUTTON"), 0),
    ACACIA_DOOR(Arrays.asList("ACACIA_DOOR_ITEM", null, null, null, null, "ACACIA_DOOR"), 0),
    ACACIA_FENCE("ACACIA_FENCE", 0),
    ACACIA_FENCE_GATE("ACACIA_FENCE_GATE", 0),
    ACACIA_LEAVES(Arrays.asList("LEAVES_2", null, null, null, null, "ACACIA_LEAVES"), 0),
    ACACIA_LOG(Arrays.asList("LOG_2", null, null, null, null, "ACACIA_LOG"), 4),
    ACACIA_PLANKS(Arrays.asList("WOOD", null, null, null, null, "ACACIA_PLANKS"), 4),
    ACACIA_PRESSURE_PLATE(Arrays.asList("WOOD_PLATE", null, null, null, null, "ACACIA_PRESSURE_PLATE"), 0),
    ACACIA_SAPLING(Arrays.asList("SAPLING", null, null, null, null, "ACACIA_SAPLING"), 4),
    ACACIA_SLAB(Arrays.asList("WOOD_STEP", null, null, null, null, "ACACIA_SLAB"), 4),
    ACACIA_STAIRS("ACACIA_STAIRS", 0),
    ACACIA_TRAPDOOR(Arrays.asList("TRAP_DOOR", null, null, null, null, "ACACIA_TRAPDOOR"), 0),
    ACACIA_WOOD(Arrays.asList("LOG_2", null, null, null, null, "ACACIA_WOOD"), 12),
    ACTIVATOR_RAIL("ACTIVATOR_RAIL", 0),
    AIR("AIR", 0),
    ALLIUM(Arrays.asList("RED_ROSE", null, null, null, null, "ALLIUM"), 1),
    ANDESITE(Arrays.asList("STONE", null, null, null, null, "ANDESITE"), 5),
    ANVIL("ANVIL", 0),
    APPLE("APPLE", 0),
    ARMOR_STAND("ARMOR_STAND", 0),
    ARROW("ARROW", 0),
    ATTACHED_MELON_STEM(Arrays.asList(null, null, null, null, null, "ATTACHED_MELON_STEM"), 0),
    ATTACHED_PUMPKIN_STEM(Arrays.asList(null, null, null, null, null, "ATTACHED_PUMPKIN_STEM"), 0),
    AZURE_BLUET(Arrays.asList("RED_ROSE", null, null, null, null, "AZURE_BLUET"), 1),
    BAKED_POTATO("BAKED_POTATO", 0),
    BARRIER("BARRIER", 0),
    BAT_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "BAT_SPAWN_EGG"), 65),
    BEACON("BEACON", 0),
    BEDROCK("BEDROCK", 0),
    BEEF(Arrays.asList("COOKED_BEEF", null, null, null, null, "BEEF"), 0),
    BEETROOT(Arrays.asList("SEEDS", null, null, null, null, "BEETROOT"), 0),
    BEETROOT_SEEDS(Arrays.asList("SEEDS", null, null, null, null, "BEETROOT_SEEDS"), 0),
    BEETROOT_SOUP(Arrays.asList("MUSHROOM_SOUP", null, null, null, null, "BEETROOT_SOUP"), 0),
    BEETROOTS(Arrays.asList("WHEAT", null, null, null, null, "BEETROOTS"), 0),
    BIRCH_BOAT(Arrays.asList("BOAT", null, null, null, null, "BIRCH_BOAT"), 0),
    BIRCH_BUTTON(Arrays.asList("WOOD_BUTTON", null, null, null, null, "BIRCH_BUTTON"), 0),
    BIRCH_DOOR(Arrays.asList("BIRCH_DOOR_ITEM", null, null, null, null, "BIRCH_DOOR"), 0),
    BIRCH_FENCE("BIRCH_FENCE", 0),
    BIRCH_FENCE_GATE("BIRCH_FENCE_GATE", 0),
    BIRCH_LEAVES(Arrays.asList("LEAVES", null, null, null, null, "BIRCH_LEAVES"), 2),
    BIRCH_LOG(Arrays.asList("LOG", null, null, null, null, "BIRCH_LOG"), 2),
    BIRCH_PLANKS(Arrays.asList("WOOD", null, null, null, null, "BIRCH_PLANKS"), 2),
    BIRCH_PRESSURE_PLATE(Arrays.asList("WOOD_PLATE", null, null, null, null, "BIRCH_PRESSURE_PLANK"), 0),
    BIRCH_SAPLING(Arrays.asList("SAPLING", null, null, null, null, "BIRCH_SAPLING"), 2),
    BIRCH_SLAB(Arrays.asList("WOOD_STEP", null, null, null, null, "BIRCH_SLAB"), 2),
    BIRCH_STAIRS(Arrays.asList("BIRCH_WOOD_STAIRS", null, null, null, null, "BIRCH_STAIRS"), 2),
    BIRCH_TRAPDOOR(Arrays.asList("TRAP_DOOR", null, null, null, null, "BIRCH_TRAPDOOR"), 0),
    BIRCH_WOOD(Arrays.asList("LOG", null, null, null, null, "BIRCH_WOOD"), 14),
    BLACK_BANNER(Arrays.asList("BANNER", null, null, null, null, "BLACK_BANNER"), 0),
    BLACK_BED(Arrays.asList("BED", null, null, null, null, "BLACK_BED"), 0),
    BLACK_CARPET(Arrays.asList("CARPET", null, null, null, null, "BLACK_CARPET"), 15),
    BLACK_CONCRETE(Arrays.asList("COAL_BLOCK", null, null, null, null, "BLACK_CONCRETE"), 0),
    BLACK_CONCRETE_POWDER(Arrays.asList("COAL_BLOCK", null, null, null, null, "BLACK_CONCRETE_POWDER"), 0),
    BLACK_GLAZED_TERRACOTTA(Arrays.asList("COAL_BLOCK", null, null, null, "BLACK_GLAZED_TERRACOTTA"), 0),
    BLACK_SHULKER_BOX(Arrays.asList("TRAPPED_CHEST", null, null, "BLACK_SHULKER_BOX"), 0),
    BLACK_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "BLACK_STAINED_GLASS"), 15),
    BLACK_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "BLACK_STAINED_GLASS_PANE"), 15),
    BLACK_TERRACOTTA(Arrays.asList("COAL_BLOCK", null, null, null, "BLACK_TERRACOTTA"), 0),
    BLACK_WOOL(Arrays.asList("WOOL", null, null, "BLACK_WOOL"), 15),
    BLAZE_POWDER("BLAZE_POWDER", 0),
    BLAZE_ROD("BLAZE_ROD", 0),
    BLAZE_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "BLAZE_SPAWN_EGG"), 61),
    BLUE_BANNER(Arrays.asList("BANNER", null, null, null, null, "BLUE_BANNER"), 4),
    BLUE_BED(Arrays.asList("BED", null, null, null, "BLUE_BED", null), 0),
    BLUE_CARPET(Arrays.asList("CARPET", null, null, "BLUE_CARPET"), 11),
    BLUE_CONCRETE(Arrays.asList("WOOL", null, null, null, "CONCRETE", "BLUE_CONCRETE"), 11),
    BLUE_CONCRETE_POWDER(Arrays.asList("WOOL", null, null, null, "CONCRETE_POWDER", "BLUE_CONCRETE_POWDER"), 11),
    BLUE_GLAZED_TERRACOTTA(Arrays.asList("LAPIS_BLOCK", null, null, null, null, "BLUE_GLAZED_TERRACOTTA"), 11),
    BLUE_ICE(Arrays.asList("PACKED_ICE", null, null, null, null, "BLUE_ICE"), 0),
    BLUE_ORCHID(Arrays.asList("RED_ROSE", null, null, null, null, "BLUE_ORCHID"), 1),
    BLUE_SHULKER_BOX(Arrays.asList("TRAPPED_CHEST", null, null, "BLUE_SHULKER_BOX"), 0),
    BLUE_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "BLUE_STAINED_GLASS"), 11),
    BLUE_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "BLUE_STAINED_GLASS_PANE"), 11),
    BLUE_TERRACOTTA(Arrays.asList("LAPIS_BLOCK", null, null, null, null, "BLUE_TERRACOTTA"), 0),
    BLUE_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "BLACK_WALL_BANNER"), 4),
    BLUE_WOOL(Arrays.asList("WOOL", null, null, "BLUE_WOOL"), 11),
    BONE("BONE", 0),
    BONE_BLOCK(Arrays.asList(null, null, "BONE_BLOCK"), 0),
    BONE_MEAL(Arrays.asList("INK_SACK", null, null, null, null, "BONE_MEAL"), 15),
    BOOK("BOOK", 0),
    BOOK_AND_QUILL(Arrays.asList("BOOK_AND_QUILL", null, null, null, null, "LEGACY_BOOK_AND_QUILL"), 0),
    BOOKSHELF("BOOKSHELF", 0),
    BOW("BOW", 0),
    BOWL("BOWL", 0),
    BRAIN_CORAL(Arrays.asList(null, null, null, null, null, "BRAIN_CORAL"), 0),
    BRAIN_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "BRAIN_CORAL_BLOCK"), 0),
    BRAIN_CORAL_FAN(Arrays.asList(null, null, null, null, null, "BRAIN_CORAL_FAN"), 0),
    BRAIN_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "BRAIN_CORAL_WALL_FAN"), 0),
    BREAD("BREAD", 0),
    BREWING_STAND("BREWING_STAND", 0),
    BREWING_STAND_ITEM(Arrays.asList("BREWING_STAND_ITEM", null, null, null, null, "BREWING_STAND"), 0),
    BRICK("BRICK", 0),
    BRICK_STAIRS("BRICK_STAIRS", 0),
    BROWN_BANNER(Arrays.asList("BANNER", null, null, null, null, "BROWN_BANNER"), 3),
    BROWN_BED(Arrays.asList("BED", null, null, null, null, "BROWN_BED"), 0),
    BROWN_CARPET(Arrays.asList("CARPET", null, null, null, null, "BROWN_CARPET"), 12),
    BROWN_CONCRETE(Arrays.asList(null, null, null, null, "", "BROWN_CONCRETE"), 0),
    BROWN_CONCRETE_POWDER(Arrays.asList(null, null, null, null, null, "BROWN_CONCRETE_POWDER"), 0),
    BROWN_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "BROWN_GLAZED_TERRACOTTA"), 0),
    BROWN_MUSHROOM("BROWN_MUSHROOM", 0),
    BROWN_MUSHROOM_BLOCK(Arrays.asList("HUGE_MUSHROOM_1", null, null, null, null, "BROWN_MUSHROOM_BLOCK"), 0),
    BROWN_SHULKER_BOX(Arrays.asList(null, null, null, "BROWN_SHULKER_BOX"), 0),
    BROWN_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "BROWN_STAINED_GLASS"), 12),
    BROWN_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "BROWN_STAINED_GLASS_PANE"), 12),
    BROWN_TERRACOTTA(Arrays.asList(null, null, null, null, null, "BROWN_TERRACOTTA"), 0),
    BROWN_WOOL(Arrays.asList("WOOL", null, null, "BROWN_WOOL"), 12),
    BUBBLE_COLUMN(Arrays.asList(null, null, null, null, null, "BUBBLE_COLUMN"), 0),
    BUBBLE_CORAL(Arrays.asList(null, null, null, null, null, "BUBBLE_CORAL"), 0),
    BUBBLE_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "BUBBLE_CORAL_BLOCK"), 0),
    BUBBLE_CORAL_FAN(Arrays.asList(null, null, null, null, null, "BUBBLE_CORAL_FAN"), 0),
    BUBBLE_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "BUBBLE_CORAL_WALL_FAN"), 0),
    BUCKET("BUCKET", 0),
    BURNING_FURNACE(Arrays.asList("BURNING_FURNACE", null, null, null, null, "LEGACY_BURNING_FURNACE"), 0),
    CACTUS("CACTUS", 0),
    CACTUS_GREEN(Arrays.asList("INK_SACK", null, null, null, null, "CACTUS_GREEN"), 2),
    CAKE("CAKE", 0),
    CAKE_BLOCK(Arrays.asList("CAKE_BLOCK", null, null, null, null, "CAKE"), 0),
    CARROT("CARROT", 0),
    CARROT_ITEM(Arrays.asList("CARROT_ITEM", null, null, null, null, "CARROT"), 0),
    CARROT_ON_A_STICK(Arrays.asList("CARROT_STICK", null, null, null, null, "CARROT_ON_A_STICK"), 0),
    CARVED_PUMPKIN(Arrays.asList("PUMPKIN", null, null, null, null, "CARVED_PUMPKIN"), 0),
    CAULDRON("CAULDRON", 0),
    CAULDRON_ITEM(Arrays.asList("CAULDRON_ITEM", null, null, null, null, "CAULDRON"), 0),
    CAVE_AIR(Arrays.asList(null, null, null, null, null, "CAVE_AIR"), 0),
    CAVE_SPIDER_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "CAVE_SPIDER_SPAWN_EGG"), 59),
    CHAIN_COMMAND_BLOCK(Arrays.asList("COMMAND", "CHAIN_COMMAND_BLOCK"), 0),
    CHAINMAIL_BOOTS("CHAINMAIL_BOOTS", 0),
    CHAINMAIL_CHESTPLATE("CHAINMAIL_CHESTPLATE", 0),
    CHAINMAIL_HELMET("CHAINMAIL_HELMET", 0),
    CHAINMAIL_LEGGINGS("CHAINMAIL_LEGGINGS", 0),
    CHARCOAL(Arrays.asList("COAL", null, null, null, null, "CHARCOAL"), 1),
    CHEST("CHEST", 0),
    CHEST_MINECART(Arrays.asList("STORAGE_MINECART", null, null, null, null, "CHEST_MINECART"), 0),
    CHICKEN(Arrays.asList("RAW_CHICKEN", null, null, null, null, "CHICKEN"), 0),
    CHICKEN_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "CHICKEN_SPAWN_EGG"), 0),
    CHIPPED_ANVIL(Arrays.asList("ANVIL", null, null, null, null, "CHIPPED_ANVIL"), 1),
    CHISELED_QUARTZ_BLOCK(Arrays.asList("QUARTZ_BLOCK", null, null, null, null, "CHISELED_QUARTZ_BLOCK"), 1),
    CHISELED_RED_SANDSTONE(Arrays.asList("RED_SANDSTONE", null, null, null, null, "CHISELED_RED_SANDSTONE"), 1),
    CHISELED_SANDSTONE(Arrays.asList("SANDSTONE", null, null, null, null, "CHISELED_SANDSTONE"), 1),
    CHISELED_STONE_BRICKS(Arrays.asList("SMOOTH_BRICK", null, null, null, null, "CHISELED_STONE_BRICKS"), 3),
    CHORUS_FLOWER(Arrays.asList(null, "CHORUS_FLOWER"), 0),
    CHORUS_FRUIT(Arrays.asList(null, "CHORUS_FRUIT"), 0),
    CHORUS_PLANT(Arrays.asList(null, "CHORUS_PLANT"), 0),
    CLAY("CLAY", 0),
    CLAY_BALL("CLAY_BALL", 0),
    CLOCK(Arrays.asList("WATCH", null, null, null, null, "CLOCK"), 0),
    COAL("COAL", 0),
    COAL_BLOCK("COAL_BLOCK", 0),
    COAL_ORE("COAL_ORE", 0),
    COARSE_DIRT(Arrays.asList("DIRT", null, null, null, null, "COARSE_DIRT"), 1),
    COBBLESTONE("COBBLESTONE", 0),
    COBBLESTONE_SLAB(Arrays.asList("STEP", null, null, null, null, "COBBLESTONE_SLAB"), 3),
    COBBLESTONE_STAIRS("COBBLESTONE_STAIRS", 0),
    COBBLESTONE_WALL(Arrays.asList("COBBLE_WALL", null, null, null, null, "COBBLESTONE_WALL"), 0),
    COBWEB(Arrays.asList("WEB", null, null, null, null, "COBWEB"), 0),
    COCOA("COCOA", 0),
    COMMAND_BLOCK(Arrays.asList("COMMAND", null, null, "COMMAND_BLOCK"), 0),
    COMMAND_BLOCK_MINECART(Arrays.asList("COMMAND_MINECART", null, null, null, "COMMAND_BLOCK_MINECART"), 0),
    COMPARATOR(Arrays.asList("REDSTONE_COMPARATOR", null, null, null, null, "COMPARATOR"), 0),
    COMPASS("COMPASS", 0),
    CONDUIT(Arrays.asList(null, null, null, null, null, "CONDUIT"), 0),
    COOKED_BEEF("COOKED_BEEF", 0),
    COOKED_CHICKEN("COOKED_CHICKEN", 0),
    COOKED_COD(Arrays.asList("COOKED_FISH", null, null, null, null, "COOKED_COD"), 0),
    COOKED_MUTTON("COOKED_MUTTON", 0),
    COOKED_PORKCHOP(Arrays.asList("GRILLED_PORK", null, null, null, null, "COOKED_PORKCHOP"), 0),
    COOKED_RABBIT("COOKED_RABBIT", 0),
    COOKED_SALMON(Arrays.asList("COOKED_FISH", null, null, null, null, "COOKED_SALMON"), 0),
    COOKIE("COOKIE", 0),
    COW_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "COW_SPAWN_EGG"), 92),
    CRACKED_STONE_BRICKS(Arrays.asList("SMOOTH_BRICK", null, null, null, null, "CRACKED_STONE_BRICKS"), 2),
    CRAFTING_TABLE(Arrays.asList("WORKBENCH", null, null, null, null, "CRAFTING_TABLE"), 0),
    CREEPER_HEAD(Arrays.asList("SKULL_ITEM", null, null, null, null, "CREEPER_HEAD"), 4),
    CREEPER_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "CREEPER_SPAWN_EGG"), 50),
    CREEPER_WALL_HEAD(Arrays.asList("SKULL", null, null, null, null, "CREEPER_WALL_HEAD"), 3),
    CUT_RED_SANDSTONE(Arrays.asList("RED_SANDSTONE", null, null, null, null, "CUT_RED_SANDSTONE"), 2),
    CUT_SANDSTONE(Arrays.asList("SANDSTONE", null, null, null, null, "CUT_SANDSTONE"), 2),
    CYAN_BANNER(Arrays.asList("BANNER", null, null, null, null, "CYAN_BANNER"), 6),
    CYAN_BED(Arrays.asList("BED", null, null, null, null, "CYAN_BED"), 0),
    CYAN_CARPET(Arrays.asList("CARPET", null, null, null, null, "CYAN_CARPET"), 9),
    CYAN_CONCRETE(Arrays.asList(null, null, null, null, "", "CYAN_CONCRETE"), 0),
    CYAN_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "", "CYAN_CONCRETE_POWDER"), 0),
    CYAN_DYE(Arrays.asList("INK_SACK", null, null, null, null, "CYAN_DYE"), 6),
    DAMAGED_ANVIL(Arrays.asList("ANVIL", null, null, null, null, "DAMAGED_ANVIL"), 2),
    DANDELION(Arrays.asList("YELLOW_FLOWER", null, null, null, null, "DANDELION"), 0),
    DANDELION_YELLOW(Arrays.asList("INK_SACK", null, null, null, null, "DANDELION_YELLOW"), 11),
    DARK_OAK_BOAT(Arrays.asList("BOAT", null, null, null, null, "DARK_OAK_BOAT"), 0),
    DARK_OAK_BUTTON(Arrays.asList("WOOD_BUTTON", null, null, null, "DARK_OAK_BUTTON"), 0),
    DARK_OAK_DOOR(Arrays.asList(null, null, null, null, null, "DARK_ORK_DOOR"), 0),
    DARK_OAK_DOOR_ITEM(Arrays.asList("DARK_OAK_DOOR_ITEM", null, null, null, null, "DARK_OAK_DOOR"), 0),
    DARK_OAK_FENCE("DARK_OAK_FENCE", 0),
    DARK_OAK_FENCE_GATE("DARK_OAK_FENCE_GATE", 0),
    DARK_OAK_LEAVES(Arrays.asList("LEAVES_2", null, null, null, null, "DARK_OAK_LEAVES"), 1),
    DARK_OAK_LOG(Arrays.asList("LOG_2", null, null, null, null, "DARK_OAK_LOG"), 1),
    DARK_OAK_PLANKS(Arrays.asList("WOOD", null, null, null, null, "DARK_OAK_PLANKS"), 5),
    DARK_OAK_PRESSURE_PLATE(Arrays.asList("WOOD_PLATE", null, null, null, null, "DARK_OAK_PRESSURE_PLATE"), 0),
    DARK_OAK_SAPLING(Arrays.asList("SAPLING", null, null, null, null, "DARK_OAK_SAPLING"), 5),
    DARK_OAK_SLAB(Arrays.asList("WOOD_STEP", null, null, null, null, "DARK_OAK_SLAB"), 5),
    DARK_OAK_STAIRS("DARK_OAK_STAIRS", 0),
    DARK_OAK_TRAPDOOR(Arrays.asList("TRAP_DOOR", null, null, null, null, "DARK_OAK_TRAPDOOR"), 0),
    DARK_OAK_WOOD(Arrays.asList("LOG_2", null, null, null, null, "DARK_OAK_WOOD"), 13),
    DARK_PRISMARINE(Arrays.asList("PRISMARINE", null, null, null, null, "DARK_PRISMARINE"), 2),
    DARK_PRISMARINE_SLAB(Arrays.asList(null, null, null, null, null, "DARK_PRISMARINE_SLAB"), 0),
    DARK_PRISMARINE_STAIRS(Arrays.asList(null, null, null, null, null, "DARK_PRISMARINE_STAIRS"), 0),
    DAYLIGHT_DETECTOR("DAYLIGHT_DETECTOR", 0),
    DEAD_BRAIN_CORAL(Arrays.asList(null, null, null, null, null, "DEAD_BRAIN_CORAL"), 0),
    DEAD_BRAIN_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "DEAD_BRAIN_CORAL_BLOCK"), 0),
    DEAD_BRAIN_CORAL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_BRAIN_CORAL_FAN"), 0),
    DEAD_BRAIN_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_BRAIN_CORAL_WALL_FAN"), 0),
    DEAD_BUBBLE_CORAL(Arrays.asList(null, null, null, null, null, "DEAD_BUBBLE_CORAL"), 0),
    DEAD_BUBBLE_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "DEAD_BUBBLE_CORAL_BLOCK"), 0),
    DEAD_BUBBLE_CORAL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_BUBBLE_CORAL_FAN"), 0),
    DEAD_BUBBLE_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_BUBBLE_CORAL_WALL_FAN"), 0),
    DEAD_BUSH("DEAD_BUSH", 0),
    DEAD_FIRE_CORAL(Arrays.asList(null, null, null, null, null, "DEAD_FIRE_CORAL"), 0),
    DEAD_FIRE_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "DEAD_FIRE_CORAL_BLOCK"), 0),
    DEAD_FIRE_CORAL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_FIRE_CORAL_FAN"), 0),
    DEAD_FIRE_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_FIRE_CORAL_WALL_FAN"), 0),
    DEAD_HORN_CORAL(Arrays.asList(null, null, null, null, null, "DEAD_HORN_CORAL"), 0),
    DEAD_HORN_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "DEAD_HORN_CORAL_BLOCK"), 0),
    DEAD_HORN_CORAL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_HORN_CORAL_FAN"), 0),
    DEAD_HORN_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "DEAD_HORN_CORAL_WALL_FAN"), 0),
    DEBUG_STICK(Arrays.asList(null, null, null, null, null, "DEBUG_STICK"), 0),
    DETECTOR_RAIL("DETECTOR_RAIL", 0),
    DIAMOND("DIAMOND", 0),
    DIAMOND_AXE("DIAMOND_AXE", 0),
    DIAMOND_BLOCK("DIAMOND_BLOCK", 0),
    DIAMOND_BOOTS("DIAMOND_BOOTS", 0),
    DIAMOND_CHESTPLATE("DIAMOND_CHESTPLATE", 0),
    DIAMOND_HELMET("DIAMOND_HELMET", 0),
    DIAMOND_HOE("DIAMOND_HOE", 0),
    DIAMOND_HORSE_ARMOR(Arrays.asList("DIAMOND_BARDING", null, null, null, null, "DIAMOND_HORSE_ARMOR"), 0),
    DIAMOND_LEGGINGS("DIAMOND_LEGGINGS", 0),
    DIAMOND_ORE("DIAMOND_ORE", 0),
    DIAMOND_PICKAXE("DIAMOND_PICKAXE", 0),
    DIAMOND_SHOVEL(Arrays.asList("DIAMOND_SPADE", null, null, null, null, "DIAMOND_SHOVEL"), 0),
    DIAMOND_SWORD("DIAMOND_SWORD", 0),
    DIORITE(Arrays.asList("STONE", null, null, null, null, "DIORITE"), 3),
    DIRT("DIRT", 0),
    DISPENSER("DISPENSER", 0),
    DOLPHIN_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "DOLPHIN_SPAWN_EGG"), 0),
    DONKEY_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "DONKEY_SPAWN_EGG"), 100),
    DRAGON_BREATH(Arrays.asList(null, "DRAGON_BREATH"), 0),
    DRAGON_HEAD(Arrays.asList(null, "SKULL", null, null, null, null, "DRAGON_HEAD"), 5),
    DRAGON_HEAD_ITEM(Arrays.asList(null, "SKULL_ITEM", null, null, null, "DRAGON_HEAD"), 5),
    DRAGON_WALL_HEAD(Arrays.asList(null, "SKULL", null, null, null, "DRAGON_WALL_HEAD"), 5),
    DRIED_KELP(Arrays.asList(null, null, null, null, null, "DRIED_KELP"), 0),
    DRIED_KELP_BLOCK(Arrays.asList(null, null, null, null, null, "DRIED_KELP_BLOCK"), 0),
    DROPPER("DROPPER", 0),
    DROWNED_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "DROWNED_SPAWN_EGG"), 0),
    EGG("EGG", 0),
    ELDER_GUARDIAN_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "ELDER_GUARDIAN_SPAWN_EGG"), 0),
    ELYTRA(Arrays.asList(null, "ELYTRA"), 0),
    EMERALD("EMERALD",0 ),
    EMERALD_BLOCK("EMERALD_BLOCK", 0),
    EMERALD_ORE("EMERALD_ORE", 0),
    ENCHANTED_BOOK("ENCHANTED_BOOK", 0),
    ENCHANTED_GOLDEN_APPLE(Arrays.asList("GOLDEN_APPLE", null, null, null, null, "ENCHANTED_GOLDEN_APPLE"), 1),
    ENCHANTING_TABLE(Arrays.asList("ENCHANTMENT_TABLE", null, null, "ENCHANTING_TABLE"), 0),
    END_CRYSTAL(Arrays.asList(null, null, null, "END_CRYSTAL"), 0),
    END_GATEWAY(Arrays.asList(null, "END_GATEWAY"), 0),
    END_PORTAL(Arrays.asList(null, null, null, null, null, "END_PORTAL"), 0),
    END_PORTAL_FRAME(Arrays.asList("ENDER_PORTAL_FRAME", "END_PORTAL_FRAME"), 0),
    END_ROD(Arrays.asList(null, "END_ROD"), 0),
    END_STONE(Arrays.asList("ENDER_STONE", "END_STONE"), 0),
    END_STONE_BRICKS(Arrays.asList(null, "END_STONE_BRICKS"), 0),
    ENDER_CHEST("ENDER_CHEST", 0),
    ENDER_EYE(Arrays.asList("EYE_OF_ENDER", "ENDER_EYE"), 0),
    ENDER_PEARL("ENDER_PEARL", 0),
    ENDERMAN_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "ENDERMAN_SPAWN_EGG"), 58),
    ENDERMITE_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "ENDERMITE_SPAWN_EGG"), 67),
    EVOKER_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "EVOKER_SPAWN_EGG"), 0),
    EXPERIENCE_BOTTLE(Arrays.asList("EXP_BOTTLE", null, null, null, null, "EXPERIENCE_BOTTLE"), 0),
    FARMLAND(Arrays.asList("SOIL", null, null, null, null, "FARMLAND"), 0),
    FEATHER("FEATHER", 0),
    FERMENTED_SPIDER_EYE("FERMENTED_SPIDER_EYE", 0),
    FERN(Arrays.asList("LONG_GRASS", null, null, null, null, "FERN"), 2),
    FILLED_MAP(Arrays.asList("MAP", null, null, null, null, "FILLED_MAP"), 0),
    FIRE("FIRE", 0),
    FIRE_CHARGE(Arrays.asList("FIREBALL", null, null, null, null, "FIRE_CHARGE"), 0),
    FIRE_CORAL(Arrays.asList(null, null, null, null, null, "FIRE_CORAL"), 0),
    FIRE_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "FIRE_CORAL_BLOCK"), 0),
    FIRE_CORAL_FAN(Arrays.asList(null, null, null, null, null, "FIRE_CORAL_FAN"), 0),
    FIRE_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "FIRE_CORAL_WALL_FAN"), 0),
    FIREWORK_ROCKET(Arrays.asList("FIREWORK", null, null, null, null, "FIREWORK_ROCKET"), 0),
    FIREWORK_STAR(Arrays.asList("FIREWORK_CHARGE", null, null, null, null, "FIREWORK_STAR"), 0),
    FISHING_ROD("FISHING_ROD", 0),
    FLINT("FLINT", 0),
    FLINT_AND_STEEL("FLINT_AND_STEEL", 0),
    FLOWER_POT("FLOWER_POT", 0),
    FLOWER_POT_ITEM(Arrays.asList("FLOWER_POT_ITEM", null, null, null, null, "FLOWER_POT"), 0),
    FROSTED_ICE(Arrays.asList(null, "FROSTED_ICE"), 0),
    FURNACE("FURNACE", 0),
    FURNACE_MINECART(Arrays.asList("POWERED_MINECART", null, null, "FURNACE_MINECART"), 0),
    GHAST_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "GHAST_SPAWN_EGG"), 56),
    GHAST_TEAR("GHAST_TEAR", 0),
    GLASS("GLASS", 0),
    GLASS_BOTTLE("GLASS_BOTTLE", 0),
    GLISTERING_MELON_SLICE(Arrays.asList("SPECKLED_MELON", null, null, null, null, "GLISTERING_MELON_SLICE"), 0),
    GLOWING_REDSTONE_ORE("GLOWING_REDSTONE_ORE", 0),
    GLOWSTONE("GLOWSTONE", 0),
    GLOWSTONE_DUST("GLOWSTONE_DUST", 0),
    GOLD_BLOCK("GOLD_BLOCK", 0),
    GOLD_INGOT("GOLD_INGOT", 0),
    GOLD_NUGGET("GOLD_NUGGET", 0),
    GOLD_ORE("GOLD_ORE", 0),
    GOLDEN_APPLE("GOLDEN_APPLE", 1),
    GOLDEN_AXE(Arrays.asList("GOLD_AXE", null, null, null, null, "GOLDEN_AXE"), 0),
    GOLDEN_BOOTS(Arrays.asList("GOLD_BOOTS", null, null, null, null, "GOLDEN_BOOTS"), 0),
    GOLDEN_CARROT("GOLDEN_CARROT", 0),
    GOLDEN_CHESTPLATE(Arrays.asList("GOLD_CHESTPLATE", null, null, null, null, "GOLDEN_CHESTPLATE"), 0),
    GOLDEN_HELMET(Arrays.asList("GOLD_HELMET", null, null, null, null, "GOLDEN_HELMET"), 0),
    GOLDEN_HOE(Arrays.asList("GOLD_HOE", null, null, null, null, "GOLDEN_HOE"), 0),
    GOLDEN_HORSE_ARMOR(Arrays.asList("GOLD_BARDING", null, null, null, null, "GOLDEN_HORSE_ARMOR"), 0),
    GOLDEN_LEGGINGS(Arrays.asList("GOLD_LEGGINGS", null, null, null, null, "GOLDEN_LEGGINGS"), 0),
    GOLDEN_PICKAXE(Arrays.asList("GOLD_PICKAXE", null, null, null, null, "GOLDEN_PICKAXE"), 0),
    GOLDEN_SHOVEL(Arrays.asList("GOLD_SPADE", null, null, null, null, "GOLDEN_SPADE"), 0),
    GOLDEN_SWORD(Arrays.asList("GOLD_SWORD", null, null, null, null, "GOLDEN_SWORD"), 0),
    GRANITE(Arrays.asList("STONE", null, null, null, null, "GRANITE"), 1),
    GRASS("GRASS", 0),
    GRASS_BLOCK(Arrays.asList("GRASS", null, null, null, null, "GRASS_BLOCK"), 0),
    GRASS_PATH(Arrays.asList(null, "GRASS_PATH"), 0),
    GRAVEL("GRAVEL", 0),
    GRAY_BANNER(Arrays.asList("BANNER", null, null, null, null, "GRAY_BANNER"), 8),
    GRAY_BED(Arrays.asList("BED", null, null, null, "GRAY_BED"), 0),
    GRAY_CARPET(Arrays.asList("CARPET", null, null, null, null, "GRAY_CARPET"), 7),
    GRAY_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "GRAY_CONCRETE"), 7),
    GRAY_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "GRAY_CONCRETE_POWDER"), 7),
    GRAY_DYE(Arrays.asList("INK_SACK", null, null, null, null, "GRAY_DYE"), 8),
    GRAY_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "GRAY_GLAZED_TERRACOTTA"), 7),
    GRAY_SHULKER_BOX(Arrays.asList(null, null, null, "GRAY_SHULKER_BOX"), 0),
    GRAY_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "GRAY_STAINED_GLASS"), 7),
    GRAY_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "GRAY_STAINED_GLASS_PANE"), 7),
    GRAY_TERRACOTTA(Arrays.asList(null, null, null, null, null, "GRAY_TERRACOTTA"), 0),
    GRAY_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "GRAY_WALL_BANNER"), 8),
    GRAY_WOOL(Arrays.asList("WOOL", null, null, "GRAY_WOOL"), 7),
    GREEN_BANNER(Arrays.asList("BANNER", null, null, null, null, "GREEN_BANNER"), 2),
    GREEN_BED(Arrays.asList("BED", null, null, null, "GREEN_BED"), 0),
    GREEN_CARPET(Arrays.asList("CARPET", null, null, null, null, "GREEN_CARPET"), 13),
    GREEN_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "GREEN_CONCRETE"), 13),
    GREEN_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "GREEN_CONCRETE_POWDER"), 13),
    GREEN_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "GREEN_GLAZED_TERRACOTTA"), 0),
    GREEN_SHULKER_BOX(Arrays.asList(null, null, null, "GREEN_SHULKER_BOX"), 0),
    GREEN_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "GREEN_STAINED_GLASS"), 13),
    GREEN_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "GREEN_STAINED_GLASS_PANE"), 13),
    GREEN_TERRACOTTA(Arrays.asList(null, null, null, null, null, "GREEN_TERRACOTTA"), 0),
    GREEN_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "GREEN_WALL_BANNER"), 2),
    GREEN_WOOL(Arrays.asList("WOOL", null, null, "GREEN_WOOL"), 13),
    GUARDIAN_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "GUARDIAN_SPAWN_EGG"), 68),
    GUNPOWDER(Arrays.asList("SULPHUR", null, null, null, null, "GUNPOWDER"), 0),
    HAY_BLOCK("HAY_BLOCK", 0),
    HEART_OF_THE_SEA(Arrays.asList(null, null, null, null, null, "HEART_OF_THE_SEA"), 0),
    HEAVY_WEIGHTED_PRESSURE_PLATE(Arrays.asList("IRON_PLATE", null, null, null, null, "HEAVY_WEIGHTED_PRESSURE_PLATE"), 0),
    HOPPER("HOPPER", 0),
    HOPPER_MINECART("HOPPER_MINECART", 0),
    HORN_CORAL(Arrays.asList(null, null, null, null, null, "HORN_CORAL"), 0),
    HORN_CORAL_BLOCK(Arrays.asList(null, null, null, null, null, "HORN_CORAL_BLOCK"), 0),
    HORN_CORAL_FAN(Arrays.asList(null, null, null, null, null, "HORN_CORAL_FAN"), 0),
    HORN_CORAL_WALL_FAN(Arrays.asList(null, null, null, null, null, "HORN_CORAL_WALL_FAN"), 0),
    HORSE_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "HORSE_SPAWN_EGG"), 100),
    HUSK_SPAWN_EGG(Arrays.asList(null, null, null, "MONSTER_EGG", null, "HUSK_SPAWN_EGG"), 60),
    ICE("ICE", 0),
    INFESTED_CHISELED_STONE_BRICKS(Arrays.asList("MONSTER_EGGS", null, null, null, null, "INFESTED_CHISELED_STONE_BRICKS"), 5),
    INFESTED_COBBLESTONE(Arrays.asList("MONSTER_EGGS", null, null, null, null, "INFESTED_COBBLESTONE"), 1),
    INFESTED_CRACKED_STONE_BRICKS(Arrays.asList("MONSTER_EGGS", null, null, null, null, "INFESTED_CRACKED_STONE_BRICKS"), 4),
    INFESTED_MOSSY_STONE_BRICKS(Arrays.asList("MONSTER_EGGS", null, null, null, null, "INFESTED_MOSSY_STONE_BRICKS"), 3),
    INFESTED_STONE(Arrays.asList("MONSTER_EGGS", null, null, null, null, "INFESTED_STONE"), 0),
    INFESTED_STONE_BRICKS(Arrays.asList("MONSTER_EGGS", null, null, null, null, "INFESTED_STONE_BRICKS"), 2),
    INK_SAC(Arrays.asList("INK_SACk", null, null, null, null, "INK_SAC"), 0),
    IRON_AXE("IRON_AXE", 0),
    IRON_BARS(Arrays.asList("IRON_FENCE", null, null, null, null, "IRON_BARS"), 0),
    IRON_BLOCK("IRON_BLOCK", 0),
    IRON_BOOTS("IRON_BOOTS", 0),
    IRON_CHESTPLATE("IRON_CHESTPLATE", 0),
    IRON_DOOR("IRON_DOOR", 0),
    IRON_DOOR_BLOCK(Arrays.asList("IRON_DOOR_BLOCK", null, null, null, null, "IRON_DOOR"), 0),
    IRON_HELMET("IRON_HELMET", 0),
    IRON_HOE("IRON_HOE", 0),
    IRON_HORSE_ARMOR(Arrays.asList("IRON_BARDING", null, null, null, null, "IRON_HORSE_ARMOR"), 0),
    IRON_INGOT("IRON_INGOT", 0),
    IRON_LEGGINGS("IRON_LEGGINGS", 0),
    IRON_NUGGET(Arrays.asList(null, null, null, "IRON_NUGGET"), 0),
    IRON_ORE("IRON_ORE", 0),
    IRON_PICKAXE("IRON_PICKAXE", 0),
    IRON_SHOVEL(Arrays.asList("IRON_SPADE", null, null, null, null, "IRON_SHOVEL"), 0),
    IRON_SWORD("IRON_SWORD", 0),
    IRON_TRAPDOOR("IRON_TRAPDOOR", 0),
    ITEM_FRAME("ITEM_FRAME", 0),
    JACK_O_LANTERN("JACK_O_LANTERN", 0),
    JUKEBOX("JUKEBOX", 0),
    JUNGLE_BOAT(Arrays.asList("BOAT", null, null, null, null, "JUNGLE_BOAT"), 0),
    JUNGLE_BUTTON(Arrays.asList("WOOD_BUTTON", null, null, null, null, "JUNGLE_BUTTON"), 0),
    JUNGLE_DOOR("JUNGLE_DOOR", 0),
    JUNGLE_DOOR_ITEM(Arrays.asList("JUNGLE_DOOR_ITEM", null, null, null, null, "JUNGLE_DOOR"), 0),
    JUNGLE_FENCE("JUNGLE_FENCE", 0),
    JUNGLE_FENCE_GATE("JUNGLE_FENCE_GATE", 0),
    JUNGLE_LEAVES(Arrays.asList("LEAVES", null, null, null, null, "JUNGLE_LEAVES"), 3),
    JUNGLE_LOG(Arrays.asList("LOG", null, null, null, null, "JUNGLE_LOG"), 3),
    JUNGLE_PLANKS(Arrays.asList("WOOD", null, null, null, null, "JUNGLE_PLANKS"), 3),
    JUNGLE_PRESSURE_PLATE(Arrays.asList("WOOD_PLATE", null, null, null, null, "JUNGLE_PRESSURE_PLATE"), 0),
    JUNGLE_SAPLING(Arrays.asList("SAPLING", null, null, null, null, "JUNGLE_SAPLING"), 3),
    JUNGLE_SLAB(Arrays.asList("WOOD_STEP", null, null, null, null, "JUNGLE_SLAB"), 3),
    JUNGLE_STAIRS(Arrays.asList("JUNGLE_WOOD_STAIRS", null, null, null, null, "JUNGLE_STAIRS"), 0),
    JUNGLE_TRAPDOOR(Arrays.asList("TRAP_DOOR", null, null, null, null, "JUNGLE_TRAPDOOR"), 0),
    JUNGLE_WOOD(Arrays.asList("LOG", null, null, null, null, "JUNGLE_WOOD"), 15),
    KELP(Arrays.asList(null, null, null, null, null, "KELP"), 0),
    KELP_PLANT(Arrays.asList(null, null, null, null, null, "KELP_PLANT"), 0),
    KNOWLEDGE_BOOK(Arrays.asList(null, null, null, null, "KNOWLEDGE_BOOK"), 0),
    LADDER("LADDER", 0),
    LAPIS_BLOCK("LAPIS_BLOCK", 0),
    LAPIS_LAZULI(Arrays.asList("INK_SACK", null, null, null, null, "LAPIS_LAZULI"), 4),
    LAPIS_ORE("LAPIS_ORE", 0),
    LARGE_FERN(Arrays.asList("DOUBLE_PLANT", null, null, null, null, "LARGE_FERN"), 3),
    LAVA("LAVA", 0),
    LAVA_BUCKET("LAVA_BUCKET", 0),
    LEAD(Arrays.asList("LEASH", null, null, null, null, "LEAD"), 0),
    LEATHER("LEATHER", 0),
    LEATHER_BOOTS("LEATHER_BOOTS", 0),
    LEATHER_CHESTPLATE("LEATHER_CHESTPLATE", 0),
    LEATHER_HELMET("LEATHER_HELMET", 0),
    LEATHER_LEGGINGS("LEATHER_LEGGINGS", 0),
    LEVER("LEVER", 0),
    LIGHT_BLUE_BANNER(Arrays.asList("BANNER", null, null, null, null, "LIGHT_BLUE_BANNER"), 12),
    LIGHT_BLUE_BED(Arrays.asList("BED", null, null, null, "LIGHT_BLUE_BED"), 0),
    LIGHT_BLUE_CARPET(Arrays.asList("CARPET", null, null, null, "LIGHT_BLUE_CARPET"), 3),
    LIGHT_BLUE_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "LIGHT_BLUE_CONCRETE"), 3),
    LIGHT_BLUE_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE", "LIGHT_BLUE_CONCRETE_POWDER"), 3),
    LIGHT_BLUE_DYE(Arrays.asList("INK_SACK", null, null, null, null, "LIGHT_BLUE_DYE"), 12),
    LIGHT_BLUE_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, "LIGHT_BLUE_GLAZED_TERRACOTTA"), 0),
    LIGHT_BLUE_SHULKER_BOX(Arrays.asList(null, null, null, "LIGHT_BLUE_SHULKER_BOX"), 0),
    LIGHT_BLUE_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "LIGHT_BLUE_STAINED_GLASS"), 3),
    LIGHT_BLUE_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "LIGHT_BLUE_STAINED_GLASS_PANE"), 3),
    LIGHT_BLUE_TERRACOTTA(Arrays.asList(null, null, null, null, null, "LIGHT_BLUE_TERRACOTTA"), 0),
    LIGHT_BLUE_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "LIGHT_BLUE_WALL_BANNER"), 12),
    LIGHT_BLUE_WOOL(Arrays.asList("WOOL", null, null, "LIGHT_BLUE_WOOL"), 3),
    LIGHT_GRAY_BANNER(Arrays.asList("BANNER", null, null, null, null, "LIGHT_GRAY_BANNER"), 7),
    LIGHT_GRAY_BED(Arrays.asList("BED", null, null, null, "LIGHT_GRAY_BED"), 0),
    LIGHT_GRAY_CARPET(Arrays.asList("CARPET", null, null, null, "LIGHT_GRAY_CARPET"), 8),
    LIGHT_GRAY_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "LIGHT_GRAY_CONCRETE"), 8),
    LIGHT_GRAY_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "LIGHT_GRAY_CONCRETE_POWDER"), 8),
    LIGHT_GRAY_DYE(Arrays.asList("INK_SACK", null, null, null, null, "LIGHT_GRAY_DYE"), 8),
    LIGHT_GRAY_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, "LIGHT_GRAY_GLAZED_TERRACOTTA"), 0),
    LIGHT_GRAY_SHULKER_BOX(Arrays.asList(null, null, null, "LIGHT_GRAY_SHULKER_BOX"), 0),
    LIGHT_GRAY_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "LIGHT_GRAY_STAINED_GLASS"), 8),
    LIGHT_GRAY_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "LIGHT_GRAY_STAINED_GLASS_PANE"), 8),
    LIGHT_GRAY_TERRACOTTA(Arrays.asList(null, null, null, null, null, "LIGHT_GRAY_TERRACOTTA"), 0),
    LIGHT_GRAY_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "LIGHT_GRAY_WALL_BANNER"), 7),
    LIGHT_GRAY_WOOL(Arrays.asList("WOOL", null, null, "LIGHT_GRAY_WOOL"), 8),
    LIGHT_WEIGHTED_PRESSURE_PLATE(Arrays.asList("GOLD_PLATE", null, null, null, null, "LIGHT_WEIGHTED_PRESSURE_PLATE"), 0),
    LILAC(Arrays.asList("DOUBLE_PLANT", null, null, null, null, "LILAC"), 1),
    LILY_PAD(Arrays.asList("WATER_LILY", null, null, null, null, "LILY_PAD"), 0),
    LIME_BANNER(Arrays.asList("BANNER", null, null, null, null, "LIME_BANNER"), 10),
    LIME_BED(Arrays.asList("BED", null, null, "LIME_BED"), 0),
    LIME_CARPET(Arrays.asList("CARPET", null, null, null, null, "LIME_CARPET"), 5),
    LIME_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "LIME_CONCRETE"), 10),
    LIME_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE", "LIME_CONCRETE_POWDER"), 10),
    LIME_DYE(Arrays.asList("INK_SACK"), 10),
    LIME_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "LIME_GLAZED_TERRACOTTA"), 0),
    LIME_SHULKER_BOX(Arrays.asList(null, null, null, "LIME_SHULKER_BOX"), 0),
    LIME_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "LIME_STAINED_GLASS"), 5),
    LIME_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "LIME_STAINED_GLASS_PANE"), 5),
    LIME_TERRACOTTA(Arrays.asList(null, null, null, null, null, "LIME_TERRACOTTA"), 0),
    LIME_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "LIME_WALL_BANNER"), 10),
    LIME_WOOL(Arrays.asList("WOOL", null, null, "LIME_WOOL"), 5),
    LINGERING_POTION(Arrays.asList(null, "LINGERING_POTION"), 0),
    LLAMA_SPAWN_EGG(Arrays.asList(null, null, null, "MONSTER_EGG", null, "LLAMA_SPAWN_EGG"), 50),
    MAGENTA_BANNER(Arrays.asList("BANNER", null, null, null, null, "MAGENTA_BANNER"), 13),
    MAGENTA_BED(Arrays.asList("BED", null, null, "MAGENTA_BED"), 0),
    MAGENTA_CARPET(Arrays.asList("CARPET", null, null, null, null, "MAGENTA_CARPET"), 2),
    MAGENTA_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "MAGENTA_CONCRETE"), 2),
    MAGENTA_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "MAGENTA_CONCRETE_POWDER"), 2),
    MAGENTA_DYE(Arrays.asList("INK_SACK", null, null, null, null, "MAGENTA_DYE"), 13),
    MAGENTA_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "MAGENTA_GLAZED_TERRACOTTA"), 0),
    MAGENTA_SHULKER_BOX(Arrays.asList(null, null, null, "MAGENTA_SHULKER_BOX"), 0),
    MAGENTA_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "MAGENTA_STAINED_GLASS"), 2),
    MAGENTA_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "MAGENTA_STAINED_GLASS_PANE"), 2),
    MAGENTA_TERRACOTTA(Arrays.asList(null, null, null, null, null, "MAGENTA_TERRACOTTA"), 0),
    MAGENTA_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "MAGENTA_WALL_BANNER"), 13),
    MAGENTA_WOOL(Arrays.asList("WOOL", null, null, "MAGENTA_WOOL"), 2),
    MAGMA_BLOCK(Arrays.asList(null, null, "MAGMA", null, null, "MAGMA_BLOCK"), 0),
    MAGMA_CREAM("MAGMA_CREAM", 0),
    MAGMA_CUBE_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "MAGMA_CUBE_SPAWN_EGG"), 62),
    MAP("MAP", 0),
    MELON(Arrays.asList("MELON_BLOCK", null, null, null, null, "MELON"), 0),
    MELON_SEEDS("MELON_SEEDS", 0),
    MELON_SLICE(Arrays.asList("MELON", null, null, null, null, "MELON_SLICE"), 0),
    MELON_STEM("MELON_STEM", 0),
    MILK_BUCKET("MILK_BUCKET", 0),
    MINECART("MINECART", 0),
    MOOSHROOM_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "MOOSHROOM_SPAWN_EGG"), 96),
    MOSSY_COBBLESTONE("MOSSY_COBBLESTONE", 0),
    MOSSY_COBBLESTONE_WALL(Arrays.asList("COBBLE_WALL", null, null, null, null, "MOSSY_COBBLESTONE_WALL"), 0),
    MOSSY_STONE_BRICKS(Arrays.asList("SMOOTH_BRICK", null, null, null, null, "MOSSY_STONE_BRICKS"), 1),
    MOVING_PISTON("MOVING_PISTON", 0),
    MULE_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "MULE_SPAWN_EGG"), 50),
    MUSHROOM_STEM(Arrays.asList(null, null, null, null, null, "MUSHROOM_STEM"), 0),
    MUSHROOM_STEW(Arrays.asList("MUSHROOM_SOUP", null, null, null, null, "MUSHROOM_STEW"), 0),
    MUSIC_DISC_11(Arrays.asList("RECORD_11", null, null, null, null, null, "MUSIC_DISC_11"), 0),
    MUSIC_DISC_13(Arrays.asList("GOLD_RECORD", null, null, null, null, null, "MUSIC_DISC_13"), 0),
    MUSIC_DISC_BLOCKS(Arrays.asList("RECORD_3", null, null, null, null, "MUSIC_DISC_BLOCKS"), 0),
    MUSIC_DISC_CAT(Arrays.asList("GREEN_RECORD", null, null, null, null, "MUSIC_DISC_RECORD"), 0),
    MUSIC_DISC_CHIRP(Arrays.asList("RECORD_4", null, null, null, null, "MUSIC_DISC_CHIRP"), 0),
    MUSIC_DISC_FAR(Arrays.asList("RECORD_5", null, null, null, null, "MUSIC_DISC_FAR"), 0),
    MUSIC_DISC_MALL(Arrays.asList("RECORD_6", null, null, null, null, "MUSIC_DISC_MALL"), 0),
    MUSIC_DISC_MELLOHI(Arrays.asList("RECORD_7", null, null, null, null, "MUSIC_DISC_MELLOHI"), 0),
    MUSIC_DISC_STAL(Arrays.asList("RECORD_8", null, null, null, null, "MUSIC_DISC_STAL"), 0),
    MUSIC_DISC_STRAD(Arrays.asList("RECORD_9", null, null, null, null, "MUSIC_DISC_STRAD"), 0),
    MUSIC_DISC_WAIT(Arrays.asList("RECORD_12", null, null, null, null, "MUSIC_DISC_WAIT"), 0),
    MUSIC_DISC_WARD(Arrays.asList("RECORD_10", null, null, null, null, "MUSIC_DISC_WARD"), 0),
    MUTTON("MUTTON", 0),
    MYCELIUM(Arrays.asList("MYCEL", null, null, null, null, "MYCELIUM"), 0),
    NAME_TAG("NAME_TAG", 0),
    NAUTILUS_SHELL(Arrays.asList(null, null, null, null, null, "NAUTILUS_SHELL"), 0),
    NETHER_BRICK(Arrays.asList("NETHER_BRICK_ITEM", null, null, null, null, "NETHER_BRICK"), 0),
    NETHER_BRICK_FENCE(Arrays.asList("NETHER_FENCE", null, null, null, null, "NETHER_BRICK_FENCE"), 0),
    NETHER_BRICK_SLAB(Arrays.asList("STEP", null, null, null, null, "NETHER_BRICK_SLAB"), 6),
    NETHER_BRICK_STAIRS(Arrays.asList("NETHER_STAIRS", null, null, null, null, "NETHER_BRICK_STAIRS"), 0),
    NETHER_BRICKS(Arrays.asList("NETHER_BRICK", null, null, null, null, "NETHER_BRICKS"), 0),
    NETHER_PORTAL(Arrays.asList("PORTAL", null, null, null, null, "NETHER_PORTAL"), 0),
    NETHER_QUARTZ_ORE(Arrays.asList("QUARTZ_ORE", null, null, null, null, "NETHER_QUARTZ_ORE"), 0),
    NETHER_STAR("NETHER_STAR", 0),
    NETHER_WART(Arrays.asList("NETHER_STALK", null, null, null, null, "NETHER_WART"), 0),
    NETHER_WART_BLOCK(Arrays.asList("NETHER_WARTS", null, null, null, null, "NETHER_WART_BLOCK"), 0),
    NETHERRACK("NETHERRACK", 0),
    NOTE_BLOCK("NOTE_BLOCK", 0),
    OAK_BOAT(Arrays.asList("BOAT", null, null, null, null, "OAK_BOAT"), 0),
    OAK_BUTTON(Arrays.asList("WOOD_BUTTON", null, null, null, null, "OAK_BUTTON"), 0),
    OAK_DOOR(Arrays.asList("WOOD_DOOR", null, null, null, null, "OAK_DOOR"), 0),
    OAK_FENCE(Arrays.asList("FENCE", null, null, null, null, "OAK_FENCE"), 0),
    OAK_FENCE_GATE(Arrays.asList("FENCE_GATE", null, null, null, null, "OAK_FENCE_GATE"), 0),
    OAK_LEAVES(Arrays.asList("LEAVES", null, null, null, null, "OAK_LEAVES"), 0),
    OAK_LOG(Arrays.asList("LOG", null, null, null, null, "OAK_LOG"), 0),
    OAK_PLANKS(Arrays.asList("WOOD", null, null, null, null, "OAK_PLANKS"), 0),
    OAK_PRESSURE_PLATE(Arrays.asList("WOOD_PLATE", null, null, null, null, "OAK_PRESSURE_PLATE"), 0),
    OAK_SAPLING(Arrays.asList("SAPLING", null, null, null, null, "OAK_SAPLING"), 0),
    OAK_SLAB(Arrays.asList("WOOD_STEP", null, null, null, null, "OAK_SLAB"), 0),
    OAK_STAIRS(Arrays.asList("WOOD_STAIRS", null, null, null, null, "OAK_STAIRS"), 0),
    OAK_TRAPDOOR(Arrays.asList("TRAP_DOOR", null, null, null, null, "OAK_TRAPDOOR"), 0),
    OAK_WOOD(Arrays.asList("LOG", null, null, null, null, "OAK_WOOD"), 12),
    OBSERVER(Arrays.asList(null, null, null, "OBSERVER"), 0),
    OBSIDIAN("OBSIDIAN", 0),
    OCELOT_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "OCELOT_SPAWN_EGG"), 98),
    ORANGE_BANNER(Arrays.asList("BANNER", null, null, null, null, "ORANGE_BANNER"), 14),
    ORANGE_BED(Arrays.asList("BED", null, null, "ORANGE_BED"), 0),
    ORANGE_CARPET(Arrays.asList("CARPET", null, null, null, null, "ORANGE_CARPET"), 1),
    ORANGE_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "ORANGE_CONCRETE"), 1),
    ORANGE_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "ORANGE_CONCRETE_POWDER"), 0),
    ORANGE_DYE(Arrays.asList("INK_SACK", null, null, null, null, "ORANGE_DYE"), 14),
    ORANGE_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "ORANGE_GLAZED_TERRACOTTA"), 0),
    ORANGE_SHULKER_BOX(Arrays.asList(null, null, null, "ORANGE_SHULKER_BOX"), 0),
    ORANGE_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "STAINED_GLASS_PANE"), 1),
    ORANGE_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "ORANGE_STAINED_GLASS_PANE"), 1),
    ORANGE_TERRACOTTA(Arrays.asList(null, null, null, null, null, "ORANGE_TERRACOTTA"), 0),
    ORANGE_TULIP(Arrays.asList("RED_ROSE", null, null, null, null, "ORANGE_TULIP"), 5),
    ORANGE_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "ORANGE_WALL_BANNER"), 14),
    ORANGE_WOOL(Arrays.asList("WOOL", null, null, "ORANGE_WOOL"), 1),
    OXEYE_DAISY(Arrays.asList("RED_ROSE", null, null, null, null, null, "OXEYE_DAISY"), 8),
    PACKED_ICE("PACKED_ICE", 0),
    PAINTING("PAINTING", 0),
    PAPER("PAPER", 0),
    PARROT_SPAWN_EGG(Arrays.asList(null, null, null, null, "MONSTER_EGG", "PARROT_SPAWN_EGG"), 50),
    PEONY(Arrays.asList("DOUBLE_PLANT", null, null, null, null, "PEONY"), 5),
    PETRIFIED_OAK_SLAB(Arrays.asList(null, null, null, null, null, "PETRIFIED_OAK_SLAB"), 0),
    PHANTOM_MEMBRANE(Arrays.asList(null, null, null, null, null, "PHANTOM_MEMBRANE"), 0),
    PHANTOM_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "PHANTOM_SPAWN_EGG"), 0),
    PIG_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "PIG_SPAWN_EGG"), 90),
    PINK_BANNER(Arrays.asList("BANNER", null, null, null, null, "PINK_BANNER"), 9),
    PINK_BED(Arrays.asList("BED", null, null, "PINK_BED"), 0),
    PINK_CARPET(Arrays.asList("CARPET", null, null, null, null, "PINK_CARPET"), 6),
    PINK_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "PINK_CONCRETE"), 6),
    PINK_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "PINK_CONCRETE_POWDER"), 6),
    PINK_DYE(Arrays.asList("INK_SACK", null, null, null, null, "PINK_DYE"), 9),
    PINK_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "PINK_GLAZED_TERRACOTTA"), 0),
    PINK_SHULKER_BOX(Arrays.asList(null, null, null, "PINK_SHULKER_BOX"), 0),
    PINK_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "PINK_STAINED_GLASS"), 6),
    PINK_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "PINK_STAINED_GLASS_PANE"), 6),
    PINK_TERRACOTTA(Arrays.asList(null, null, null, null, null, "PINK_TERRACOTTA"), 0),
    PINK_TULIP(Arrays.asList("RED_ROSE", null, null, null, null, "PINK_TULIP"), 7),
    PINK_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "PINK_WALL_BANNER"), 9),
    PINK_WOOL(Arrays.asList("WOOL", null, null, "PINK_WOOL"), 6),
    PISTON(Arrays.asList("PISTON_BASE", null, null, null, null, "PISTON"), 0),
    PISTON_HEAD(Arrays.asList("PISTON_EXTENSION", null, null, null, null, "PISTON_HEAD"), 0),
    PLAYER_HEAD(Arrays.asList("SKULL", null, null, null, null, "PLAYER_HEAD"), 3),
    PLAYER_HEAD_ITEM(Arrays.asList("SKULL_ITEM", null, null, null, null, "PLAYER_HEAD"), 3),
    PLAYER_WALL_HEAD(Arrays.asList("SKULL", null, null, null, null, "PLAYER_WALL_HEAD"), 3),
    PODZOL(Arrays.asList("DIRT", null, null, null, null, "PODZOL"), 2),
    POISONOUS_POTATO("POISONOUS_POTATO", 0),
    POLAR_BEAR_SPAWN_EGG(Arrays.asList(null, null, "MONSTER_EGG", null, null, "POLAR_BEAR_SPAWN_EGG"), 50),
    POLISHED_ANDESITE(Arrays.asList("STONE", null, null, null, null, "POLISHED_ANDESITE"), 6),
    POLISHED_DIORITE(Arrays.asList("STONE", null, null, null, null, "POLISHED_DIORITE"), 4),
    POLISHED_GRANITE(Arrays.asList("STONE", null, null, null, null, "PLOISHED_GRANITE"), 2),
    POPPED_CHORUS_FRUIT(Arrays.asList(null, "POPPED_CHORUS_FRUIT"), 0),
    POPPY(Arrays.asList("RED_ROSE", null, null, null, null, "POPPY"), 0),
    PORKCHOP(Arrays.asList("PORK", null, null, null, null, "PORKCHOP"), 0),
    POTATO_ITEM(Arrays.asList("POTATO_ITEM", null, null, null, null, "POTATO"), 0),
    POTATOES(Arrays.asList("POTATO", null, null, null, null, "POTATOES"), 0),
    POTION("POTION", 0),
    // todo - Create a UMaterial that takes MaterialData, or can set ItemMeta
    // todo - Create a UMaterial for potions, arrows, etc
    POTTED_ACACIA_SAPLING(Arrays.asList(null, null, null, null, null, "POTTED_ACACIA_SAPLING"), 0),
    POTTED_ALLIUM(Arrays.asList(null, null, null, null, null, "POTTED_ALLIUM"), 0),
    POTTED_AZURE_BLUET(Arrays.asList(null, null, null, null, null, "POTTED_AZURE_BLUET"), 0),
    POTTED_BIRCH_SAPLING(Arrays.asList(null, null, null, null, null, "POTTED_BIRCH_SAPLING"), 0),
    POTTED_BLUE_ORCHID(Arrays.asList(null, null, null, null, null, "POTTED_BLUE_ORCHID"), 0),
    POTTED_BROWN_MUSHROOM(Arrays.asList(null, null, null, null, null, "POTTED_BROWN_MUSHROOM"), 0),
    POTTED_CACTUS(Arrays.asList(null, null, null, null, null, "POTTED_CACTUS"), 0),
    POTTED_DANDELION(Arrays.asList(null, null, null, null, null, "POTTED_DANDELION"), 0),
    POTTED_DARK_OAK_SAPLING(Arrays.asList(null, null, null, null, null, "POTTED_DARK_OAK_SAPLING"), 0),
    POTTED_DEAD_BUSH(Arrays.asList(null, null, null, null, null, "POTTED_DEAD_BUSH"), 0),
    POTTED_FERN(Arrays.asList(null, null, null, null, null, "POTTED_FERN"), 0),
    POTTED_JUNGLE_SAPLING(Arrays.asList(null, null, null, null, null, "POTTED_JUNGLE_SAPLING"), 0),
    POTTED_OAK_SAPLING(Arrays.asList(null, null, null, null, null, "POTTED_OAK_SAPLING"), 0),
    POTTED_ORANGE_TULIP(Arrays.asList(null, null, null, null, null, "POTTED_ORANGE_TULIP"), 0),
    POTTED_OXEYE_DAISY(Arrays.asList(null, null, null, null, null, "POTTED_OXEYE_DAISY"), 0),
    POTTED_PINK_TULIP(Arrays.asList(null, null, null, null, null, "POTTED_PINK_TULIP"), 0),
    POTTED_POPPY(Arrays.asList(null, null, null, null, null, "POTTED_POPPY"), 0),
    POTTED_RED_MUSHROOM(Arrays.asList(null, null, null, null, null, "POTTED_RED_MUSHROOM"), 0),
    POTTED_RED_TULIP(Arrays.asList(null, null, null, null, null, "POTTED_RED_TULIP"), 0),
    POTTED_SPRUCE_SAPLING(Arrays.asList(null, null, null, null, null, "POTTED_SPRUCE_SAPLING"), 0),
    POTTED_WHITE_TULIP(Arrays.asList(null, null, null, null, null, "POTTED_WHITE_TULIP"), 0),
    POWERED_RAIL("POWERED_RAIl", 0),
    PRISMARINE("PRISMARINE", 0),
    PRISMARINE_BRICK_SLAB(Arrays.asList(null, null, null, null, null, "PRISMARINE_BRICK_SLABS"), 0),
    PRISMARINE_BRICK_STAIRS(Arrays.asList(null, null, null, null, null, "PRISMARINE_BRICK_STAIRS"), 0),
    PRISMARINE_BRICKS(Arrays.asList("PRISMARINE", null, null, null, null, "PRISMARINE_BRICKS"), 1),
    PRISMARINE_CRYSTALS("PRISMARINE_CRYSTALS", 0),
    PRISMARINE_SHARD("PRISMARINE_SHARD", 0),
    PRISMARINE_SLAB(Arrays.asList(null, null, null, null, null, "PRISMARINE_SLAB"), 0),
    PRISMARINE_STAIRS(Arrays.asList(null, null, null, null, null, "PRISMARINE_STAIRS"), 0),
    PUFFERFISH(Arrays.asList("RAW_FISH", null, null, null, null, "PUFFERFISH"), 3),
    PUFFERFISH_BUCKET(Arrays.asList(null, null, null, null, null, "PUFFERFISH_BUCKET"), 0),
    PUFFERFISH_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "PUFFERFISH_SPAWN_EGG"), 0),
    PUMPKIN("PUMPKIN", 0),
    PUMPKIN_PIE("PUMPKIN_PIE", 0),
    PUMPKIN_SEEDS("PUMPKIN_SEEDS", 0),
    PUMPKIN_STEM("PUMPKIN_STEM", 0),
    PURPLE_BANNER(Arrays.asList("BANNER", null, null, null, null, "PURPLE_BANNER"), 5),
    PURPLE_BED(Arrays.asList("BED", null, null, "PURPLE_BED"), 0),
    PURPLE_CARPET(Arrays.asList("CARPET", null, null, null, null, "PURPLE_CARPET"), 10),
    PURPLE_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "PURPLE_CONCRETE"), 10),
    PURPLE_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE_POWDER", "PURPLE_CONCRETE_POWDER"), 10),
    PURPLE_DYE(Arrays.asList("INK_SACK", null, null, null, null, "PURPLE_DYE"), 5),
    PURPLE_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "PURPLE_GLAZED_TERRACOTTA"), 0),
    PURPLE_SHULKER_BOX(Arrays.asList(null, null, null, "PURPLE_SHULKER_BOX"), 0),
    PURPLE_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "PURPLE_STAINED_GLASS"), 10),
    PURPLE_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "PURPLE_STAINED_GLASS_PANE"), 10),
    PURPLE_TERRACOTTA(Arrays.asList(null, null, null, null, null, "PURPLE_TERRACOTTA"), 0),
    PURPLE_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "PURPLE_WALL_BANNER"), 5),
    PURPLE_WOOL(Arrays.asList("WOOL", null, null, null, null, "PURPLE_WOOL"), 10),
    PURPUR_BLOCK(Arrays.asList(null, "PURPUR_BLOCK"), 0),
    PURPUR_PILLAR(Arrays.asList(null, "PURPUR_PILLAR"), 0),
    PURPUR_SLAB(Arrays.asList(null, "PURPUR_SLAB"), 0),
    PURPUR_STAIRS(Arrays.asList(null, "PURPUR_STAIRS"), 0),
    QUARTZ("QUARTZ", 0),
    QUARTZ_BLOCK("QUARTZ_BLOCK", 0),
    QUARTZ_PILLAR("QUARTZ_PILLAR", 0),
    QUARTZ_SLAB(Arrays.asList("STEP", null, null, null, null, "QUARTZ_SLAB"), 7),
    QUARTZ_STAIRS("QUARTZ_STAIRS", 0),
    RABBIT("RABBIT", 0),
    RABBIT_FOOT("RABBIT_FOOT", 0),
    RABBIT_HIDE("RABBIT_HIDE", 0),
    RABBIT_STEW("RABBIT_STEW", 0),
    RAIL(Arrays.asList("RAILS", null, null, null, null, "RAIL"), 0),
    RED_BANNER(Arrays.asList("BANNER", null, null, null, null, "RED_BANNER"), 1),
    RED_BED(Arrays.asList("BED", null, null, "RED_BED"), 0),
    RED_CARPET(Arrays.asList("CARPET", null, null, null, null, "RED_CARPET"), 14),
    RED_CONCRETE(Arrays.asList(null, null, null, null, "CONCRETE", "RED_CONCRETE"), 14),
    RED_CONCRETE_POWDER(Arrays.asList(null, null, null, null, "CONCRETE", "RED_CONCRETE_POWDER"), 14),
    RED_GLAZED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "RED_GLAZED_TERRACOTTA"), 0),
    RED_MUSHROOM("RED_MUSHROOM", 0),
    RED_MUSHROOM_BLOCK(Arrays.asList("HUGE_MUSHROOM_2", null, null, null, null, "RED_MUSHROOM_BLOCK"), 14),
    RED_NETHER_BRICKS(Arrays.asList(null, null, "RED_NETHER_BRICK", null, null, "RED_NETHER_BRICKS"), 0),
    RED_SAND(Arrays.asList("SAND", null, null, null, null, "RED_SAND"), 1),
    RED_SANDSTONE("RED_SANDSTONE", 0),
    RED_SANDSTONE_SLAB(Arrays.asList("STONE_SLAB2", null, null, null, null, "RED_SANDSTONE_SLAB"), 0),
    RED_SANDSTONE_STAIRS("RED_SANDSTONE_STAIRS", 0),
    RED_SHULKER_BOX(Arrays.asList(null, null, null, "RED_SHULKER_BOX"), 0),
    RED_STAINED_GLASS(Arrays.asList("STAINED_GLASS", null, null, null, null, "RED_STAINED_GLASS"), 14),
    RED_STAINED_GLASS_PANE(Arrays.asList("STAINED_GLASS_PANE", null, null, null, null, "RED_STAINED_GLASS_PANE"), 14),
    RED_TERRACOTTA(Arrays.asList(null, null, null, null, null, "RED_TERRACOTTA"), 0),
    RED_TULIP(Arrays.asList("RED_ROSE", null, null, null, null, "RED_TULIP"), 4),
    RED_WALL_BANNER(Arrays.asList("BANNER", null, null, null, null, "RED_WALL_BANNER"), 1),
    RED_WOOL(Arrays.asList("WOOL", null, null, "RED_WOOL"), 14),
    REDSTONE("REDSTONE", 0),
    REDSTONE_BLOCK("REDSTONE_BLOCK", 0),
    REDSTONE_LAMP(Arrays.asList("REDSTONE_LAMP_OFF", null, null, null, null, "REDSTONE_LAMP"), 0),
    REDSTONE_LAMP_ON(Arrays.asList("REDSTONE_LAMP_ON", null, null, null, null, "REDSTONE_LAMP_ON"), 0),
    REDSTONE_ORE("REDSTONE_ORE", 0),
    REDSTONE_TORCH(Arrays.asList("REDSTONE_TORCH_OFF", null, null, null, null, "REDSTONE_TORCH"), 0),
    REDSTONE_TORCH_ON(Arrays.asList("REDSTONE_TORCH_ON", null, null, null, null, "REDSTONE_TORCH"), 0),
    REDSTONE_WALL_TORCH(Arrays.asList("REDSTONE_TORCH_OFF", null, null, null, null, "REDSTONE_WALL_TORCH"), 0),
    REDSTONE_WIRE("REDSTONE_WIRE", 0),
    REPEATER(Arrays.asList("DIODE", null, null, null, null, "REPEATER"), 0),
    REPEATING_COMMAND_BLOCK(Arrays.asList("COMMAND", "REPEATING_COMMAND_BLOCK"), 0),
    ROSE_BUSH(Arrays.asList("DOUBLE_PLANT", null, null, null, null, "ROSE_BUSH"), 4),
    ROSE_RED(Arrays.asList("INK_SACK", null, null, null, null, "ROSE_RED"), 1),
    ROTTEN_FLESH("ROTTEN_FLESH", 0),
    SADDLE("SADDLE", 0),
    SALMON(Arrays.asList("RAW_FISH", null, null, null, null, "SALMON"), 1),
    SALMON_BUCKET(Arrays.asList(null, null, null, null, null, "SALMON_BUCKET"), 0),
    SALMON_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "SALMON_SPAWN_EGG"), 0),
    SAND("SAND", 0),
    SANDSTONE("SANDSTONE", 0),
    SANDSTONE_SLAB(Arrays.asList("STEP", null, null, null, null, "SANDSTONE_SLAB"), 1),
    SANDSTONE_STAIRS("SANDSTONE_STAIRS", 0),
    SCUTE(Arrays.asList(null, null, null, null, null, "SCUTE"), 0),
    SEA_LANTERN("SEA_LANTERN", 0),
    SEA_PICKLE(Arrays.asList(null, null, null, null, null, "SEA_PICKEL"), 0),
    SEAGRASS(Arrays.asList(null, null, null, null, null, "SEAGRASS"), 0),
    SHEARS("SHEARS", 0),
    SHEEP_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "SHEEP_SPAWN_EGG"), 91),
    SHIELD(Arrays.asList(null, "SHIELD"), 0),
    SHULKER_BOX(Arrays.asList(null, null, null, "SHULKER_BOX"), 0),
    SHULKER_SHELL(Arrays.asList(null, null, null, "SHULKER_SHELL"), 0),
    SHULKER_SPAWN_EGG(Arrays.asList(null, null, null, "MONSTER_EGG", null, "SHULKER_SPAWN_EGG"), 50),
    SIGN("SIGN", 0),
    SIGN_POST(Arrays.asList("SIGN_POST", null, null, null, null, "SIGN"), 0),
    SILVERFISH_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "SILVERFISH_SPAWN_EGG"), 60),
    SKELETON_HORSE_SPAWN_EGG(Arrays.asList(null, null, null, null, null, "SKELETON_HORSE_SPAWN_EGG"), 0),
    SKELETON_SKULL(Arrays.asList("SKULL", null, null, null, null, "SKELETON_SKULL"), 0),
    SKELETON_SKULL_ITEM(Arrays.asList("SKULL_ITEM", null, null, null, null, "SKELETON_SKULL"), 0),
    SKELETON_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "SKELETON_SPAWN_EGG"), 51),
    SKELETON_WALL_SKULL(Arrays.asList("SKULL", null, null, null, null, "SKELETON_WALL_SKULL"), 0),
    SLIME_BALL("SLIME_BALL", 0),
    SLIME_BLOCK("SLIME_BLOCK", 0),
    SLIME_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "SLIME_SPAWN_EGG"), 55),
    SMOOTH_QUARTZ(Arrays.asList("QUARTZ_BLOCK", null, null, null, null, "SMOOTH_QUARTZ"), 0),
    SMOOTH_RED_SANDSTONE(Arrays.asList("DOUBLE_STONE_SLAB2", null, null, null, null, "SMOOTH_RED_SANDSTONE"), 8),
    SMOOTH_SANDSTONE(Arrays.asList("DOUBLE_STONE_SLAB", null, null, null, null, "SMOOTH_SANDSTONE"), 9),
    SMOOTH_STONE(Arrays.asList("DOUBLE_STONE_SLAB", null, null, null, null, "SMOOTH_STONE"), 8),
    SNOW("SNOW", 0),
    SNOW_BLOCK("SNOW_BLOCK", 0),
    SNOWBALL(Arrays.asList("SNOW_BALL", null, null, null, null, "SNOWBALL"), 0),
    SOUL_SAND("SOUL_SAND", 0),
    SPAWNER(Arrays.asList("MOB_SPAWNER", null, null, null, null, "SPAWNER"), 0),
    SPECTRAL_ARROW(Arrays.asList("ARROW", "SPECTRAL_ARROW"), 0),
    SPIDER_EYE("SPIDER_EYE", 0),
    SPIDER_SPAWN_EGG(Arrays.asList("MONSTER_EGG", null, null, null, null, "SPIDER_SPAWN_EGG"), 52),
    SPLASH_POTION(Arrays.asList(null, "SPLASH_POTION"), 0),
    SPONGE("SPONGE", 0),
    SPRUCE_BOAT(Arrays.asList("BOAT", null, null, null, null, "SPRUCE_BOAT"), 0),
    SPRUCE_BUTTON(Arrays.asList("WOOD_BUTTON", null, null, null, null, "SPRUCE_BUTTON"), 0),
    SPRUCE_DOOR("SPRUCE_DOOR", 0),
    SPRUCE_DOOR_ITEM(Arrays.asList("SPRUC_DOOR_ITEM", null, null, null, null, "SPRUCE_DOOR"), 0),
    SPRUCE_FENCE("SPRUCE_FENCE", 0),
    SPRUCE_FENCE_GATE("SPRUCE_FENCE_GATE", 0),
    ;
    private final ArrayList<String> names = new ArrayList<>();
    private final String version = Bukkit.getVersion();
    private ItemStack is;
    UMaterial(String name, int data) {
        names.add(name);
        final Material m = Material.valueOf(name);
        is = version.contains("1.8") || version.contains("1.9") || version.contains("1.10") || version.contains("1.11") || version.contains("1.12") ? new ItemStack(m, 1, (byte) data) : new ItemStack(m);
    }
    UMaterial(List<String> names, int data) {
        this.names.addAll(names);
        int ver = version.contains("1.8") ? 0 : version.contains("1.9") ? 1 : version.contains("1.10") ? 2 : version.contains("1.11") ? 3 : version.contains("1.12") ? 4 : version.contains("1.13") ? 5 : version.contains("1.14") ? 6 : names.size()-1;
        int realver = ver;
        if(names.get(ver) == null) {
            for(int i = ver; i >= 0; i--) {
                if(names.get(ver) != null)
                    realver = i;
            }
        }
        // 0 = 1.8.8
        // 1 = 1.9.4
        // 2 = 1.10.2
        // 3 = 1.11.2
        // 4 = 1.12.2
        // 5 = 1.13.2
        // 6 = 1.14.0
        if(names.get(realver) != null) {
            is = new ItemStack(Material.valueOf(names.get(realver)), 1, (byte) data);
        }
    }
    public ItemStack getItemStack() { return is; }


    @Deprecated
    public static ItemStack valueOf(String name, byte data) {
        name = name.toUpperCase();
        for(UMaterial u : UMaterial.values()) {
            if(u.names.contains(name)) {
                final ItemStack i = u.getItemStack();
                if(i.getData().getData() == data)
                    return i;
            }
        }
        return null;
    }
}
